name: cd-chain

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*.*.*'

jobs:
  quickcheck:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.rustversion.outputs.rustversion }}
    steps:
    - uses: actions/checkout@v2
    - run: cargo check
    - run: cargo pkgid
    - run: 'echo "$(cargo pkgid | cut -d# -f2)"'
    - id: rustversion
      run: 'echo "::set-output name=rustversion::$(cargo pkgid | cut -d# -f2)"'

  update_release_draft:
    needs: quickcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Build deb package
        run: cargo deb
      - name: Check repo directory
        run: ls -lha
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:               
          tag_name: ${{ echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' }} # Strip git ref prefix from version
          draft: true
          prerelease: false
          files: ./target/debian/beast_${{needs.quickcheck.outputs.version}}_amd64.deb
